// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Draftline.Gateway.Stores;

#nullable disable

namespace Draftline.Gateway.Migrations
{
    [DbContext(typeof(DraftlineDbContext))]
    [Migration("20260616011420_AddGroupNameAndPermissions")]
    partial class AddGroupNameAndPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Draftline.Gateway.Stores.AuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("audit_id");

                    b.Property<string>("BatchKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_key");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<int>("Flow")
                        .HasColumnType("integer")
                        .HasColumnName("flow");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("AuditId");

                    b.HasIndex("Flow", "EmployeeId", "WindowStart", "WindowEnd")
                        .HasDatabaseName("idx_audit_lookup");

                    b.ToTable("audit_records");
                });

            modelBuilder.Entity("Draftline.Gateway.Stores.BatchRegistry", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<int>("Flow")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("BatchId");

                    b.HasIndex("Flow", "GroupName")
                        .HasDatabaseName("idx_batch_registry_lookup");

                    b.ToTable("BatchRegistries");
                });

            modelBuilder.Entity("Draftline.Gateway.Stores.ExceptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("Flow")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RowKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceBatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SuspendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Flow", "GroupName")
                        .HasDatabaseName("idx_exception_lookup");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("Draftline.Gateway.Stores.OperationLogEntity", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_ip");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<int>("Flow")
                        .HasColumnType("integer")
                        .HasColumnName("flow");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("form_name");

                    b.Property<DateTime>("OperatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("operated_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.HasKey("LogId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_oplog_employee");

                    b.HasIndex("OperatedAt")
                        .HasDatabaseName("idx_oplog_time");

                    b.ToTable("operation_logs");
                });

            modelBuilder.Entity("Draftline.Gateway.Stores.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Flow")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_user_permission_employee");

                    b.ToTable("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
